Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

NumericLiterals:
  Enabled: false

LineLength:
  Max: 360

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

CaseIndentation:
  IndentWhenRelativeTo: case
  IndentOneStep: true

WordArray:
  MinSize: 100

RedundantSelf:
  Enabled: false

MethodLength:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

GuardClause:
  Enabled: false

UnusedMethodArgument:
  Enabled: false

UnusedBlockArgument:
  Enabled: false
