default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: samgrah
  password: samgrah

development:
  <<: *default
  database: samgrah_dev

test:
  <<: *default
  database: samgrah_test

production:
  <<: *default
  database: samgrah
